# Generated by Django 4.2.20 on 2025-05-07 19:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PeerConnect', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 14, 19, 22, 30, 275756, tzinfo=datetime.timezone.utc)),
        ),
    ]
