# Generated by Django 4.2.18 on 2025-04-23 00:50

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PeerConnect', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.CharField(blank=True, choices=[('spring', 'Spring'), ('fall', 'Fall'), ('summer', 'Summer')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='year',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)]),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 30, 0, 50, 9, 786508, tzinfo=datetime.timezone.utc)),
        ),
    ]
