# Generated by Django 5.1.7 on 2025-04-01 22:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PeerConnect', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 8, 22, 11, 52, 67028, tzinfo=datetime.timezone.utc)),
        ),
    ]
