# Generated by Django 5.1.7 on 2025-05-04 22:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PeerConnect', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 11, 22, 18, 7, 950921, tzinfo=datetime.timezone.utc)),
        ),
    ]
