# Generated by Django 5.1.6 on 2025-04-29 23:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PeerConnect', '0002_alter_assessment_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='predefined_questions',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='num_questions',
        ),
        migrations.AlterField(
            model_name='assessment',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 6, 23, 6, 27, 191466, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='course',
            name='semester',
            field=models.CharField(blank=True, choices=[('spring', 'Spring'), ('fall', 'Fall'), ('summer', 'Summer'), ('winter', 'Winter')], max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name='PredefinedQuestion',
        ),
    ]
