# Generated by Django 4.2.18 on 2025-04-24 15:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PeerConnect', '0002_course_semester_course_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionresponse',
            name='evaluated_student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluations_received', to='PeerConnect.studentprofile'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 1, 15, 15, 8, 359466, tzinfo=datetime.timezone.utc)),
        ),
    ]
