# Generated by Django 4.2.20 on 2025-05-07 19:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PeerConnect', '0002_alter_assessment_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 14, 19, 22, 50, 845680, tzinfo=datetime.timezone.utc)),
        ),
    ]
