# Generated by Django 5.1.6 on 2025-04-25 14:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PeerConnect', '0003_questionresponse_evaluated_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 2, 14, 29, 23, 494576, tzinfo=datetime.timezone.utc)),
        ),
    ]
