# Generated by Django 4.2.20 on 2025-04-25 15:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PeerConnect', '0003_questionresponse_evaluated_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 2, 15, 18, 4, 731013, tzinfo=datetime.timezone.utc)),
        ),
    ]
