# Generated by Django 5.1.7 on 2025-04-01 22:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PeerConnect', '0004_alter_assessment_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 8, 22, 24, 32, 248433, tzinfo=datetime.timezone.utc)),
        ),
    ]
