# Generated by Django 5.1.7 on 2025-03-29 16:47

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PeerConnect', '0004_alter_course_professor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='questions',
        ),
        migrations.AddField(
            model_name='assessment',
            name='available_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='assessment',
            name='self_assessment',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 5, 16, 47, 55, 394820, tzinfo=datetime.timezone.utc)),
        ),
    ]
