# Generated by Django 4.2.18 on 2025-04-30 17:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PeerConnect', '0004_alter_assessment_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 7, 17, 16, 47, 688154, tzinfo=datetime.timezone.utc)),
        ),
    ]
