# Generated by Django 5.1.6 on 2025-05-05 01:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PeerConnect', '0005_alter_assessment_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='open_reminder_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 12, 1, 20, 14, 955158, tzinfo=datetime.timezone.utc)),
        ),
    ]
