# Generated by Django 5.1.7 on 2025-03-30 18:57

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PeerConnect', '0005_remove_assessment_questions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='PeerConnect.team'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 6, 18, 57, 13, 917611, tzinfo=datetime.timezone.utc)),
        ),
    ]
