# Generated by Django 5.1.7 on 2025-03-30 19:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PeerConnect', '0006_assessment_team_alter_assessment_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='course',
        ),
        migrations.AlterField(
            model_name='assessment',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 6, 19, 42, 46, 814461, tzinfo=datetime.timezone.utc)),
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='team',
        ),
        migrations.AddField(
            model_name='assessment',
            name='course',
            field=models.ManyToManyField(related_name='forms', to='PeerConnect.course'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='team',
            field=models.ManyToManyField(blank=True, null=True, related_name='assessments', to='PeerConnect.team'),
        ),
    ]
