# Generated by Django 5.1.6 on 2025-05-06 20:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PeerConnect', '0006_assessment_open_reminder_sent_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assessment',
            old_name='open_reminder_sent',
            new_name='available_reminder_sent',
        ),
        migrations.AddField(
            model_name='assessment',
            name='due_soon_reminder_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 13, 20, 12, 50, 155139, tzinfo=datetime.timezone.utc)),
        ),
    ]
