# Generated by Django 5.1.7 on 2025-04-08 22:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PeerConnect', '0006_alter_assessment_due_date_questionresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 15, 22, 2, 30, 825864, tzinfo=datetime.timezone.utc)),
        ),
    ]
