# Generated by Django 5.1.7 on 2025-04-08 22:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PeerConnect', '0007_assessment_published_alter_assessment_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 15, 22, 9, 42, 371970, tzinfo=datetime.timezone.utc)),
        ),
    ]
