# Generated by Django 5.1.7 on 2025-03-30 19:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PeerConnect', '0007_remove_assessment_course_alter_assessment_due_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='course',
            field=models.ManyToManyField(related_name='assessments', to='PeerConnect.course'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 6, 19, 49, 11, 91772, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='team',
            field=models.ManyToManyField(blank=True, related_name='assessments', to='PeerConnect.team'),
        ),
    ]
