# Generated by Django 5.1.6 on 2025-03-30 20:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PeerConnect', '0008_alter_assessment_course_alter_assessment_due_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 6, 20, 10, 40, 368029, tzinfo=datetime.timezone.utc)),
        ),
    ]
