# Generated by Django 4.2.18 on 2025-04-08 22:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PeerConnect', '0008_alter_assessment_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 15, 22, 39, 12, 238202, tzinfo=datetime.timezone.utc)),
        ),
    ]
