# Generated by Django 5.1.6 on 2025-04-09 20:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PeerConnect', '0009_alter_assessment_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 16, 20, 29, 27, 198382, tzinfo=datetime.timezone.utc)),
        ),
    ]
