# Generated by Django 5.1.6 on 2025-03-30 21:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PeerConnect', '0010_alter_assessment_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='num_questions',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 6, 21, 27, 0, 703735, tzinfo=datetime.timezone.utc)),
        ),
    ]
