# Generated by Django 5.1.6 on 2025-04-14 15:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PeerConnect', '0011_alter_assessment_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 21, 15, 18, 38, 951122, tzinfo=datetime.timezone.utc)),
        ),
    ]
