# Generated by Django 5.1.6 on 2025-03-30 21:35

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PeerConnect', '0011_assessment_num_questions_alter_assessment_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 6, 21, 35, 57, 949364, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('order', models.PositiveIntegerField()),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='PeerConnect.assessment')),
            ],
        ),
    ]
