# Generated by Django 5.1.6 on 2025-03-30 23:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PeerConnect', '0012_alter_assessment_due_date_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredefinedQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='assessment',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 6, 23, 33, 15, 327931, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='assessment',
            name='predefined_questions',
            field=models.ManyToManyField(blank=True, to='PeerConnect.predefinedquestion'),
        ),
    ]
