# Generated by Django 5.1.6 on 2025-04-15 01:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PeerConnect', '0012_alter_assessment_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 22, 1, 49, 10, 801870, tzinfo=datetime.timezone.utc)),
        ),
    ]
