# Generated by Django 5.1.6 on 2025-03-30 22:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PeerConnect', '0012_alter_assessment_due_date_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 6, 22, 21, 19, 940608, tzinfo=datetime.timezone.utc)),
        ),
    ]
