# Generated by Django 5.1.6 on 2025-04-15 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PeerConnect', '0013_alter_assessment_due_date'),
        ('PeerConnect', '0013_alter_assessment_due_date_courseinvitation'),
    ]

    operations = [
    ]
