# Generated by Django 5.1.7 on 2025-03-31 01:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PeerConnect', '0013_predefinedquestion_alter_assessment_due_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 7, 1, 1, 20, 658439, tzinfo=datetime.timezone.utc)),
        ),
    ]
