# Generated by Django 5.1.6 on 2025-03-31 02:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PeerConnect', '0014_alter_assessment_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('likert', 'Likert Scale'), ('open', 'Open-Ended')], default='open', max_length=10),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 7, 2, 57, 20, 396693, tzinfo=datetime.timezone.utc)),
        ),
    ]
