# Generated by Django 5.1.6 on 2025-04-15 13:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PeerConnect', '0014_merge_20250415_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 22, 13, 31, 47, 509801, tzinfo=datetime.timezone.utc)),
        ),
    ]
