# Generated by Django 5.1.7 on 2025-03-31 12:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PeerConnect', '0015_question_question_type_alter_assessment_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 7, 12, 21, 54, 82172, tzinfo=datetime.timezone.utc)),
        ),
    ]
