# Generated by Django 5.1.6 on 2025-04-15 16:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PeerConnect', '0016_alter_assessment_due_date_professorprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professorprofile',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 22, 16, 37, 41, 104772, tzinfo=datetime.timezone.utc)),
        ),
    ]
