# Generated by Django 5.1.6 on 2025-04-17 21:22

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PeerConnect', '0017_professorprofile_active_studentprofile_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 24, 21, 22, 28, 105644, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments_created', to='PeerConnect.professorprofile'),
        ),
        migrations.AlterField(
            model_name='course',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses_taught', to='PeerConnect.professorprofile'),
        ),
        migrations.AlterField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(related_name='courses_enrolled', to='PeerConnect.studentprofile'),
        ),
        migrations.AlterField(
            model_name='questionresponse',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='PeerConnect.studentprofile'),
        ),
        migrations.AlterField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(related_name='teams', to='PeerConnect.studentprofile'),
        ),
    ]
