# Generated by Django 5.1.7 on 2025-03-31 13:36

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PeerConnect', '0017_alter_assessment_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='professor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='assessments_created', to='PeerConnect.userprofile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assessment',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 7, 13, 28, 40, 945063, tzinfo=datetime.timezone.utc)),
        ),
    ]
