# Generated by Django 5.1.6 on 2025-03-31 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PeerConnect', '0013_alter_assessment_due_date'),
        ('PeerConnect', '0018_assessment_professor_alter_assessment_due_date'),
    ]

    operations = [
    ]
