# Generated by Django 5.1.6 on 2025-03-31 14:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PeerConnect', '0018_assessment_professor_alter_assessment_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 7, 14, 29, 36, 101111, tzinfo=datetime.timezone.utc)),
        ),
    ]
