# Generated by Django 5.1.6 on 2025-03-31 15:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PeerConnect', '0019_merge_20250331_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 7, 15, 5, 24, 797336, tzinfo=datetime.timezone.utc)),
        ),
    ]
