# Generated by Django 4.2.18 on 2025-04-02 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PeerConnect', '0019_merge_20250331_1505'),
        ('PeerConnect', '0020_alter_assessment_due_date_questionresponse'),
    ]

    operations = [
    ]
