# Generated by Django 5.1.6 on 2025-03-31 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PeerConnect', '0019_alter_assessment_due_date'),
        ('PeerConnect', '0020_alter_assessment_due_date'),
    ]

    operations = [
    ]
