# Generated by Django 5.1.6 on 2025-03-31 15:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PeerConnect', '0021_merge_20250331_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 7, 15, 31, 20, 151992, tzinfo=datetime.timezone.utc)),
        ),
    ]
