# Generated by Django 4.2.18 on 2025-04-02 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PeerConnect', '0021_merge_20250402_2047'),
        ('PeerConnect', '0022_alter_assessment_due_date'),
    ]

    operations = [
    ]
