# Generated by Django 4.2.18 on 2025-04-02 20:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PeerConnect', '0023_merge_20250402_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 9, 20, 51, 8, 783625, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('open', 'Open-Ended'), ('likert', 'Likert Scale')], default='open', max_length=10),
        ),
    ]
